directories:
  output: dist-electron
  buildResources: build
appId: com.antigravity.pharmacy
productName: PharmaPro
files:
  - filter:
      - dist/**/*
      - electron/**/*
mac:
  category: public.app-category.business
  target:
    - dmg
win:
  target:
    - nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 39.2.3
